# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-04 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20180304_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackQuestionnaireProvider',
            new_name='FeedbackQuestionnaireB2P',
        ),
        migrations.AlterModelOptions(
            name='feedbackquestionnaireb2p',
            options={'verbose_name': 'FeedbackQuestionnaire to Provider', 'verbose_name_plural': 'FeedbackQuestionnaires to Provider'},
        ),
    ]
