# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-05 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20180304_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='assignment',
            field=models.TextField(blank=True, null=True, verbose_name='\u8bfe\u540e\u4f5c\u4e1a'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='content',
            field=models.TextField(verbose_name='\u8bfe\u7a0b\u5927\u7eb2'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='copy_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Plan', verbose_name='\u6e90\u81ea'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='materialhtml',
            field=models.TextField(blank=True, null=True, verbose_name='\u8bfe\u4ef6\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='materiallinks',
            field=models.TextField(blank=True, null=True, verbose_name='\u8bfe\u4ef6\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='slides',
            field=models.TextField(blank=True, null=True, verbose_name='\u8bfe\u4ef6'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.IntegerField(verbose_name='\u6559\u6848\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sumy',
            field=models.TextField(blank=True, null=True, verbose_name='\u603b\u7ed3'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='voc',
            field=models.TextField(blank=True, null=True, verbose_name='\u751f\u8bcd'),
        ),
        migrations.AlterField(
            model_name='reviewtoprovider',
            name='questionnaire',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
