# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-05 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20180305_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.IntegerField(choices=[(0, '\u672a\u5907\u8bfe'), (1, '\u5f85\u5ba1\u6838'), (2, '\u672a\u901a\u8fc7'), (3, '\u5df2\u5907\u8bfe')], verbose_name='\u6559\u6848\u72b6\u6001'),
        ),
    ]
