# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20180305_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='materialhtml',
            field=models.TextField(blank=True, null=True, verbose_name='\u8bfe\u4ef6\u7f51\u9875'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='roomlink',
            field=models.URLField(blank=True, null=True, verbose_name='\u4e0a\u8bfe\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Topic'),
        ),
    ]
