# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20180306_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Topic'),
        ),
    ]
