# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_testmodelformfk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodelformfk',
            name='provider',
        ),
        migrations.AddField(
            model_name='testmodelformfk',
            name='sku',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Sku'),
        ),
        migrations.AddField(
            model_name='testmodelformfk',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Topic'),
            preserve_default=False,
        ),
    ]
