# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-13 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20180307_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPayoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Provider')),
            ],
            options={
                'verbose_name': 'ProviderPayoff',
                'verbose_name_plural': 'ProviderPayoffs',
            },
        ),
        migrations.AlterField(
            model_name='sku',
            name='status',
            field=models.IntegerField(choices=[(0, '\u53ef\u7ea6'), (1, b'\xe5\xb7\xb2\xe7\xba\xa6'), (2, b'\xe5\xbe\x85\xe6\x8a\xa2'), (3, b'\xe6\xb2\xa1\xe6\x9c\x89\xe6\x95\x99\xe5\xb8\x88\xe4\xba\x86'), (4, b'\xe5\xb7\xb2\xe5\xae\x9a'), (5, b'\xe5\xb7\xb2\xe5\xa4\x87\xe8\xaf\xbe'), (6, b'\xe8\x80\x81\xe5\xb8\x88ready'), (7, b'\xe5\xad\xa6\xe7\x94\x9f\xe8\xbf\x9b\xe4\xba\x86\xe6\x95\x99\xe5\xae\xa4'), (8, b'\xe5\xbe\x85\xe8\xaf\x84\xe4\xbb\xb7'), (9, b'\xe5\xb7\xb2\xe7\xbb\x93\xe6\x9d\x9f '), (10, b'\xe5\xad\xa6\xe7\x94\x9f\xe5\x8f\x96\xe6\xb6\x88')], default=0),
        ),
        migrations.AddField(
            model_name='providerpayoff',
            name='skus',
            field=models.ManyToManyField(to='main.Sku'),
        ),
    ]
