# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-13 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20180313_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerpayoff',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providerpayoff',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providerpayoff',
            name='currency',
            field=models.IntegerField(default=0),
        ),
    ]
