# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-10 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20180313_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='info_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Sku'),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.IntegerField(choices=[(0, b'\xe7\x99\xbb\xe9\x99\x86'), (1, b'\xe7\x99\xbb\xe5\x87\xba'), (2, b'\xe4\xb8\x8b\xe5\x8d\x95'), (3, b'\xe4\xbf\xae\xe6\x94\xb9'), (4, b'\xe5\x8f\x96\xe6\xb6\x88'), (5, b'\xe8\xae\xa1\xe7\xae\x97\xe5\x8a\xb3\xe8\xb5\x84'), (6, b'\xe6\x8f\x90\xe5\x8f\x96\xe5\xb7\xa5\xe8\xb5\x84')]),
        ),
    ]
