# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-17 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20180410_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='activity_action',
            field=models.IntegerField(blank=True, choices=[(10, '\u767b\u9646(+1)'), (-10, '\u8d8524h\u672a\u767b\u9646(-2)'), (20, '\u661f\u671f\u4e9424\u70b9\u524d\u66f4\u65b0\u4e0b\u5468\u8bfe\u8868(+1)'), (21, '1h\u5185\u786e\u8ba4\u63a5\u5355\uff08+1\uff09'), (22, '\u4e0a\u5b8c\u8bfe\uff08+1\uff09'), (23, '\u4e0a\u5b8c\u8bfe15\u5206\u949f\u5185\u5b8c\u6210\u6559\u5e08\u8bc4\u4ef7\uff08+1\uff09'), (24, '\u7ed3\u675f\u8bfe\u7a0b\u540e1h\u5185\u66f4\u65b0\u75c5\u4f8b\uff08+1\uff09'), (25, 'trial lesson\u540e\u9996\u6b21\u7f16\u5199\u5b66\u751f\u75c5\u4f8b\uff08+1\uff09'), (26, '\u62a2\u5355\uff08+5\uff09'), (-20, '\u672a\u53ca\u65f6\u66f4\u65b0\u8bfe\u8868\uff08-5\uff09'), (-21, '5\u5c0f\u65f6\u5185\u672a\u63a5\u5355\u6216\u53d6\u6d88\u8ba2\u5355\uff08-15\uff09'), (-22, '\u653e\u5f03\u8ba2\u5355\uff08-20\uff09'), (-23, '\u62a2\u5355\u9664\u5916\u6ca1\u63d0\u524d24\u5c0f\u65f6\u5907\u8bfe\uff08-10\uff09'), (-24, '\u6ca1\u53bb\u4e0a\u8bfe\uff08-30\uff09'), (-25, '\u8fdf\u5230\uff08-5\uff09'), (30, '30min\u5185\u56de\u7b54\u5b66\u751f\u95ee\u9898\uff08+1\uff09'), (-30, '\u672a\u56de\u7b54\u5b66\u751f\u95ee\u9898\uff08-2\uff09')], null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='activity_change',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
