# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-18 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20180417_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
