# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_buyer_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='active_community',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='active_course',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='active_daily',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
