# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-26 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20180426_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actlog',
            name='log',
        ),
        migrations.AddField(
            model_name='actlog',
            name='log',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.Log'),
            preserve_default=False,
        ),
    ]
